'use strict';
const $=s=>document.querySelector(s); const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
let activity,items=[],position=0,score=0,answered=false,answers=[],selected=null;
$('#total').textContent='١٠٤ تدريبات + تحدٍّ شامل';
$('#activity-list').innerHTML=bank.map((b,i)=>`<div class="activity"><span class="index">المحطة ${i+1} / ${b.mixed?'٢٠':b.items.length} سؤالًا</span><h3>${b.title}</h3><p>${b.subtitle}</p><button class="primary" data-start="${b.id}">ابدأ التدريب</button></div>`).join('');
document.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>start(b.dataset.start));
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));$('#activities').hidden=b.dataset.tab!=='activities';$('#lesson').hidden=b.dataset.tab!=='lesson'});
function start(id){activity=bank.find(b=>b.id===id);let pool=activity.items;if(activity.mixed)pool=[...shuffle(bank[0].items).slice(0,7),...shuffle(bank[2].items).slice(0,7),...shuffle(bank[3].items).slice(0,6)];items=shuffle(pool).map(q=>{let order=shuffle(q.options.map((_,i)=>i));return {...q,options:order.map(i=>q.options[i]),answer:order.indexOf(q.answer)}});position=0;score=0;answers=[];$('#home').hidden=true;$('#play').hidden=false;render();}
function render(){answered=false;selected=null;const q=items[position];const mode=activity.mode;$('#play').innerHTML=`<div class="quiz-card"><div class="quiz-top"><h2>${activity.title}</h2><button class="secondary" id="exit">العودة للمحطات</button></div><div class="quiz-top"><span>السؤال ${position+1} من ${items.length}</span><span>درجتك: <strong>${score}</strong></span></div><div class="progress" role="progressbar" aria-label="التقدم" aria-valuemin="0" aria-valuemax="${items.length}" aria-valuenow="${position}"><div style="width:${position/items.length*100}%"></div></div><h3 class="question">${esc(q.q)}</h3><div id="interaction"></div><div id="feedback" aria-live="polite"></div><button class="primary next" id="next" hidden>${position===items.length-1?'اعرض نتيجتي':'السؤال التالي'}</button></div>`;
$('#exit').onclick=()=>{if(answers.length&&!confirm('العودة ستنهي هذه المحاولة دون حفظ نتيجتها. هل تريد العودة؟'))return;$('#play').hidden=true;$('#home').hidden=false};
if(mode==='drag'){$('#interaction').innerHTML=`<p class="note">اسحب الكلمة إلى مجموعتها، أو اضغط الكلمة ثم المجموعة.</p><button class="token" data-value="0" aria-pressed="false">${esc(q.token)}</button><div class="drops">${q.options.map((o,i)=>`<button class="drop" data-answer="${i}">${esc(o)}</button>`).join('')}</div>`;setupDrag(false)}
else if(mode==='fill'){$('#interaction').innerHTML=`<p class="note">اسحب الإجابة إلى الفراغ، أو اضغط الإجابة ثم الفراغ.</p><div class="options">${q.options.map((o,i)=>`<button class="token" data-value="${i}" aria-pressed="false">${esc(o)}</button>`).join('')}</div><button class="drop" id="blank" style="width:100%">ضع الإجابة هنا (…) </button>`;setupDrag(true)}
else{$('#interaction').innerHTML=`<div class="options">${q.options.map((o,i)=>`<button class="option" data-answer="${i}">${esc(o)}</button>`).join('')}</div>`;document.querySelectorAll('.option').forEach(b=>b.onclick=()=>answer(+b.dataset.answer))}
$('#next').onclick=()=>{position++;position===items.length?finish():render()};}
function answer(choice){if(answered)return;answered=true;const q=items[position],ok=choice===q.answer;if(ok)score++;answers.push({q,choice,ok});document.querySelectorAll('#interaction button').forEach(b=>{b.disabled=true;if(b.dataset.answer!==undefined)b.classList.add(+b.dataset.answer===q.answer?'correct':+b.dataset.answer===choice?'wrong':'locked')});if($('#blank')){$('#blank').textContent=q.options[choice];$('#blank').classList.add(ok?'correct':'wrong')};$('#feedback').innerHTML=`<div class="feedback ${ok?'correct':'wrong'}"><strong>${ok?'أحسنت! إجابة صحيحة (+١)':'محاولة جيدة، لنتعلّم من الخطأ'}</strong><p>${ok?'':`الإجابة الصحيحة: <b>${esc(q.options[q.answer])}</b><br>`}${esc(q.why)}</p></div>`;$('#next').hidden=false;}
function setupDrag(fill){const tokens=[...document.querySelectorAll('.token')];const targets=[...document.querySelectorAll('.drop')];function select(b){selected=+b.dataset.value;tokens.forEach(t=>{t.classList.toggle('selected',t===b);t.setAttribute('aria-pressed',String(t===b))})}function drop(t){if(selected===null||answered)return;answer(fill?selected:+t.dataset.answer)}tokens.forEach(b=>{b.onclick=()=>{if(!answered)select(b)};b.onpointerdown=e=>{if(answered||e.button!==0)return;select(b);const startX=e.clientX,startY=e.clientY;let ghost=null;b.setPointerCapture(e.pointerId);const move=ev=>{if(!ghost&&Math.hypot(ev.clientX-startX,ev.clientY-startY)<6)return;if(!ghost){ghost=b.cloneNode(true);ghost.removeAttribute('id');ghost.classList.add('drag-ghost');ghost.setAttribute('aria-hidden','true');document.body.append(ghost)}ghost.style.left=ev.clientX+'px';ghost.style.top=ev.clientY+'px';const t=document.elementFromPoint(ev.clientX,ev.clientY)?.closest('.drop');targets.forEach(x=>x.classList.toggle('over',x===t))};const end=ev=>{const t=document.elementFromPoint(ev.clientX,ev.clientY)?.closest('.drop');if(ev.type==='pointerup'&&ghost&&t)drop(t);ghost?.remove();targets.forEach(x=>x.classList.remove('over'));b.removeEventListener('pointermove',move);b.removeEventListener('pointerup',end);b.removeEventListener('pointercancel',end)};b.addEventListener('pointermove',move);b.addEventListener('pointerup',end);b.addEventListener('pointercancel',end)}});targets.forEach(t=>t.onclick=()=>drop(t));}
function finish(){const pct=Math.round(score/items.length*100),wrong=answers.filter(a=>!a.ok);$('#play').innerHTML=`<div class="result"><span class="eyebrow">أكملت ${activity.title}</span><h2>${pct>=90?'مبدع في عالم الهمزات!':pct>=70?'أحسنت، تقدّم جميل!':'واصل التدرّب، أنت قادر على الإتقان!'}</h2><div class="score"><div>${score}<small> / ${items.length}</small></div></div><p>نسبة الإجابات الصحيحة: <strong>${pct}٪</strong></p><p class="note">الدرجة محسوبة من المحاولة الأولى لكل سؤال في هذا النشاط.</p><label for="student">اسم الطالب لإضافته إلى رسالة المعلم</label><br><input id="student" required type="text" maxlength="70" autocomplete="name" placeholder="اكتب اسمك"><div class="result-actions"><a class="share" id="share" target="_blank" rel="noopener noreferrer">شارك درجتك مع المعلم</a><button class="secondary" id="retry">أعد المحاولة</button><button class="secondary" id="back">جميع المحطات</button></div><p class="note">يفتح واتساب برسالتك ودرجتك، ثم تضغط إرسال.</p>${wrong.length?`<details class="review"><summary>راجع الأسئلة التي تحتاج إلى تدريب (${wrong.length})</summary><ol>${wrong.map(a=>`<li><b>${esc(a.q.q)}</b><br>إجابتك: ${esc(a.q.options[a.choice])}<br>الصواب: ${esc(a.q.options[a.q.answer])}<br>${esc(a.q.why)}</li>`).join('')}</ol></details>`:'<p>أجبت عن جميع الأسئلة إجابة صحيحة. رائع!</p>'}</div>`;function link(){const name=$('#student').value.trim();let msg=`السلام عليكم أستاذ مقرن،${name?' أنا الطالب '+name:''}\nأنهيت نشاط «${activity.title}» في درس همزتي الوصل والقطع وهمزتي ابن وابنة.\nدرجتي: ${score} من ${items.length} (${pct}٪).`;$('#share').href='https://wa.me/966593300313?text='+encodeURIComponent(msg)}link();$('#student').oninput=link;$('#share').onclick=e=>{if(!$('#student').value.trim()){e.preventDefault();$('#student').reportValidity();$('#student').focus()}};$('#retry').onclick=()=>start(activity.id);$('#back').onclick=()=>{$('#play').hidden=true;$('#home').hidden=false};}
